### ISSUE TITLE
Suggestion: Physics Mod Compatibility (Ragdoll API)

### ISSUE THREAD

**Issue by SkyTheNerd** [Blancworks/Figura#142]
Since Figura version 2.1.2 of Haubna's Physics mod, The Figura Mod has not been Compatible with the physics mod, But The Creator Created A Ragdoll API, So I am suggesting adding support because there is no hurt in asking
link to the GitHub repository [here](https://github.com/haubna/PhysicsMod)

**Comment by MCAlexisYT** [comment]
That's an interesting idea...
