### ISSUE TITLE
RIGHT_HELD_ITEM makes the Item appear in the Left Hand instead of the right one

### ISSUE THREAD

**Issue by PinkuRinku** [Blancworks/Figura#143]
Main Hand (Right Hand)
![image](https://user-images.githubusercontent.com/69436960/125650818-29af225a-d575-4761-8132-438bfaff5ea6.png)

Offhand with LEFT_HELD_ITEM
![image](https://user-images.githubusercontent.com/69436960/125651015-9b582c47-faf4-4f0c-9e55-d9445bb4762a.png)

**Comment by Francy-chan** [comment]
Ensure that the `LEFT_HELD_ITEM` and `RIGHT_HELD_ITEM` blockbench keywords are inside the proper `LEFT_ARM` and `RIGHT_ARM` groups

Can you also:
* send a screenshot of your blockbench groups
or
* attach the respective avatar

**Comment by PinkuRinku** [comment]
Sure.
Here are my Blockbench groups.
![image](https://user-images.githubusercontent.com/69436960/125682365-6830dea4-d18d-4b20-a3a6-5c70826a6eac.png)

Here my whole Avatar
[AmongUsFiguraAvatar.zip](https://github.com/Blancworks/Figura/files/6818569/AmongUsFiguraAvatar.zip)

I am pretty sure that I have everything in the right location

**Comment by Francy-chan** [comment]
issue was caused by optifine
optifine is not supported by figura
