### ISSUE TITLE
Saving a model works differently between 0.0.5 and the latest prerelease

### ISSUE THREAD

**Issue by owenxm** [Blancworks/Figura#144]
In the attached file, on 0.0.5, enabling test through blockbench and then saving the model will make flower go down. Disabling test through blockbench and saving the model will make flower go back up.
However, in the latest prerelease, enabling test through blockbench and then saving the model will make flower go down, but then disabling test through blockbench and saving the model will not make flower go back up.

[flowerhead - Copy.zip](https://github.com/Blancworks/Figura/files/6819472/flowerhead.-.Copy.zip)

**Comment by TheOneTrueZandra** [comment]
What do you mean by "Test Through Blockbench"??

**Comment by owenxm** [comment]
disabling and enabling test, the model part, with blockbench. The eye button?
![highlighted](https://user-images.githubusercontent.com/78569181/125828336-9af50783-7228-4671-a3c1-e4e934829ded.png)
As described in my initial comment, the script file should make flower, the model part, go down or up depending on whether test is enabled or disabled. In 0.0.5, you could do this with just blockbench, however, in the latest prerelease extra scripting is required.

**Comment by TheOneTrueZandra** [comment]
@Francy-chan Does this have to do with the changes you made to getEnabled for blockbench?

**Comment by Francy-chan** [comment]
maybe, but probably not, because this only affects if it should be rendered or not
the cube being shifted up/down based on another cube in the same group seems to be an issue, which well, seems to be fixed
