### ISSUE TITLE
Crouching Script Breaks Torso

### ISSUE THREAD

**Issue by Sothopery** [Blancworks/Figura#146]
Hello! This mod is amazing and I can't wait for you to expand it! I have a few issues that should be fixed, and maybe a suggestion too,

You see, when I put this script in to change positions while SNEAKING, it works fine.
![cool](https://user-images.githubusercontent.com/36519325/126009390-a9a32682-1d20-4e02-ad8c-6f33b9b86dcc.gif)

But when I change the MIMIC TORSO's, they snap out of place.
![not so cool](https://user-images.githubusercontent.com/36519325/126009443-a41fa29a-c6b0-414b-8e2d-009e5c4336b9.gif)
and I've tried to offset it with the "else" function, but it snaps back strangely as well.

Not very cool. I wish it would be fixed! 

Also some suggestions :D if you havent already, maybe a SITTING animation would be nice... and the ability to change how your hand looks in First-Person mode!

**Comment by Sothopery** [comment]
Also, here: the model
[Cloaked Creeper.zip](https://github.com/Blancworks/Figura/files/6833435/Cloaked.Creeper.zip)

**Comment by Sothopery** [comment]
Version: 1.16.5
Optifine is NOT installed
![image](https://user-images.githubusercontent.com/36519325/126009894-bce9e1b5-7b8f-4baf-87b7-de22008f4843.png)

**Comment by TheOneTrueZandra** [comment]
This isn't a bug. Changing the value to move the torso... Is supposed to move the torso. If you're looking to change something else or modify the pivot, you're going to need to actually do that.

Feel free to join the discord to get some more help.
