### ISSUE TITLE
Model ignoring pivots?

### ISSUE THREAD

**Issue by snailmann32** [Blancworks/Figura#151]
I'm not sure if I'm doing something wrong but it seems like pivots I specified in blockbench for the player model are being ignored as the groups rotate and move unexpectedly. I've attached the figura files and a demonstration video to explain what I'm talking about. Let me know if anything else is needed!
[night.zip](https://github.com/Blancworks/Figura/files/6941086/night.zip)

https://user-images.githubusercontent.com/65823603/128407222-87b65b9b-d6bb-43cd-ae05-9fc634b693a6.mp4

**Comment by TheOneTrueZandra** [comment]
Parent keyword parts ignore pivots, which is intentional.

If you wish to respect pivots, you'll have to use the MIMIC parts, which respect pivots, but ignore the translation of a part.

**Comment by snailmann32** [comment]
Oh, thank you!
