### ISSUE TITLE
figura avatars are not visible in multiplayer for other players

### ISSUE THREAD

**Issue by RoyalCrayfish** [Blancworks/Figura#155]
figura avatars are not visible in multiplayer for other players

**Comment by ElectricDaFearox** [comment]
Are you using any mods that affect rendering?

**Comment by RoyalCrayfish** [comment]
> Are you using any mods that affect rendering?

iris-mc1.17-1.1.1, EntityCulling-Fabric-1.3.3

**Comment by RoyalCrayfish** [comment]
Just checked the mod does not work even on a clean build

**Comment by MCAlexisYT** [comment]
They probably doesn't have the Figura mod installed

**Comment by FlamesEC** [comment]
Are you using optifine, or are you in an offline server? (Server that permits access to cracked players)

**Comment by RoyalCrayfish** [comment]
> Are you using optifine, or are you in an offline server? (Server that permits access to cracked players)

there is no optifine and the server in an offline

**Comment by DraconicLuca** [comment]
Figura doesn't work on cracked accounts. Others won't be able to see it

**Comment by foxotic** [comment]
Will add that it has been reported using Optifine + Optifabric currently does not allow visibility of other player models in 1.17.1. Using latest optifabric and stable G9 build of optifine

**Comment by TheOneTrueZandra** [comment]
Closing this as it seems like the server was cracked.
