### ISSUE TITLE
I don’t know how to set the camera height to correctly match the height of the model

### ISSUE THREAD

**Issue by miaotouy** [Blancworks/Figura#159]
When I use it with First-person Model, I can see my head when I lower my head
![2021-08-24_11 34 31](https://user-images.githubusercontent.com/66715028/130551697-6f5a6ce6-ed28-4263-a18e-5118d833e4f6.png)

**Comment by Capiosus** [comment]
This would break compatibility with servers if you could change eye height.

**Comment by GrandpaScout** [comment]
You can use `camera.FIRST_PERSON.setPos({x, y, z})` to move the first person camera.
This will *not* change your aim, however.

Also, if you are using FPM, you will always see `MIMIC_HEAD`s. You should probably switch to using a `HEAD` or `Head` keyword to hide the head properly, or you can hide it while in first-person with a script.

I would also recommend joining the [Blancworks Discord server](https://discord.gg/blancworks) for help with things like this, there are plenty of people there that are willing to answer questions.
