### ISSUE TITLE
Incompatability with Fabric Capes

### ISSUE THREAD

**Issue by Y3flamex** [Blancworks/Figura#160]
When i load a figure, the cape on Fabric Capes doesn't display anymore
[latest (1).txt](https://github.com/Blancworks/Figura/files/7071003/latest.1.txt)

**Comment by CookiePlays0** [comment]
This is because using the blockbench keywords `Torso` or `TORSO` disables the cape

**Comment by Mattabase** [comment]
My cape seems to disappear if I apply any model at all, I have not tested with just Figura, but I am no using a cape mod, it is my vanilla migration cape.
