### ISSUE TITLE
Suffix/Prefix Broken in chat

### ISSUE THREAD

**Issue by CookiePlays0** [Blancworks/Figura#175]
the suffix/prefix does not show up in chat for players with custom names

Tab: https://cookies.life-is-pa.in/5hmbliXhk

Chat: https://cookies.life-is-pa.in/5hmbfrVqK

fix pls so i get cheese

**Comment by skye5000** [comment]
fix pls so i get cheese

**Comment by Francy-chan** [comment]
paper/spigot/custom server issue

**Fabric Singleplayer:**
![image](https://user-images.githubusercontent.com/40085587/144695428-1550b7d9-e8a4-40da-b56a-db86240797d3.png)

**Fabric Multiplayer:**
![image](https://user-images.githubusercontent.com/40085587/144695459-f520851f-5b7d-4217-aca9-1e6975510ea2.png)

**Comment by CookiePlays0** [comment]
OH RIGHT I FORGOR ITS SETTING
