### ISSUE TITLE
Request: A parent type that attaches to the camera

### ISSUE THREAD

**Issue by Khodyn** [Blancworks/Figura#179]
No, I don't mean the existing `CAMERA` type as that looks at the camera. In my opinion a parent type shouldn't do that and it's something that should be player-scripted rather than hardcoded but now that everyone's using it, I guess it's too late to change it's behavior.

I am requesting a parent type that attaches the part to the camera and renders it, even in first person. I have done this manually with a NO_PARENT part in world_render() (render() lags 1 frame behind, oversight?) but every couple of seconds it visibly detaches because of a race condition with the script being ran in a background thread.

**Comment by Manuel-3** [comment]
The ``CAMERA`` keyword rotates the group towards the camera of the player seeing it, meaning its rotation is different for every instance of the script running. There is currently no way of getting the player executing the script (the ``player`` variable is the player using the script) so it can't be custom scripted. (Also, why requiring people to make it manually, if Figura can just handle it inernally, so I think ``CAMERA`` keyword is a good thing)

As for whatever race condition problem you have, I don't know whats going on here, might just be a bug in your code?

**Comment by Khodyn** [comment]
> As for whatever race condition problem you have, I don't know whats going on here, might just be a bug in your code?

Figura runs Lua scripts off the main thread. This is why if you put a long _for_ loop in render, world_render or tick it will not cause a framerate drop, instead the avatar parts themselves will appear to lag as the function is forced to run at a lower rate. There is an edge case where world_render() doesn't finish running in time for Minecraft to begin rendering the next frame which causes the part I have attached to the camera to appear 'detached' every so often.

https://user-images.githubusercontent.com/49518050/145975547-ef0ebf00-48a4-4f1a-bee4-14bd8fd999cb.mp4

**Comment by Francy-chan** [comment]
The HUD keyword should fix that
