### ISSUE TITLE
Crash rendering enchanted item with render layer in 0.0.8 pre-release

### ISSUE THREAD

**Issue by Khodyn** [Blancworks/Figura#182]
Avatar to reproduce:
[EnchantedRenderCrash.zip](https://github.com/Blancworks/Figura/files/7760730/EnchantedRenderCrash.zip)

Crash report:
[crash-2021-12-22_18.18.54-client.txt](https://github.com/Blancworks/Figura/files/7760747/crash-2021-12-22_18.18.54-client.txt)

**Comment by Francy-chan** [comment]
fixed!
