### ISSUE TITLE
Using the action wheel while inside other UI breaks UI

### ISSUE THREAD

**Issue by EliasRonefors** [Blancworks/Figura#186]
Using the Figura action wheel while inside basically any interface(like chests, barrels, inventory etc...) breaks the UI as seen in pictures attached below.
![image](https://user-images.githubusercontent.com/90244703/148114067-58558883-cf02-4b0b-aaf5-7a15c9cfd835.png)
![image](https://user-images.githubusercontent.com/90244703/148114158-71eb35cd-d061-41cf-8703-38c9fa050509.png)
![image](https://user-images.githubusercontent.com/90244703/148114282-cfae3f4e-9c8a-452e-a63d-f80a188285b4.png)

I have noticed this same issue does not appear in the Game Menu or any of the settings menus nor while in a bed.

**Comment by Francy-chan** [comment]
well you shouldnt be able to open the action wheel while inside other menus, anyway, thats fixed on 0.0.8 pre-releases
