### ISSUE TITLE
basic lua keywords/functions work incorrectly

### ISSUE THREAD

**Issue by pjalsGit** [Blancworks/Figura#191]
keywords like `..` (or is it the tostring function, im not entirely sure) are working incorrectly, like with this example:

```lua
local config = {
    ["minRandomness"] = {-50, -50, -50},
    ["maxRandomness"] =  {50, 50, 50}
}


print("Loading chaos...")

local function serialise(t, indent, brackets)
    if brackets == nil then
        brackets = true
    end
    local indent = indent or "  "
    if type(t) == "table" then
        if brackets then
            print("{")
        end
        for k,v in pairs(t) do
            if type(v) == "table" then
                print(indent .. k .. ": {")
                serialise(v, "  "..indent, false)
                print(indent .. "},")
            else
                print(indent .. tostring(k) .. ": " .. tostring(v) .. ",")
            end
        end
        if brackets then
            print("}")
        end
    else
        print(indent .. tostring(t))
    end
end

print("Chaos configuration: ") serialise(config)
```

lua repl prints:
```lua
{
  maxRandomness: {
    1: 50,
    2: 50,
    3: 50,
  },
  minRandomness: {
    1: -50,
    2: -50,
    3: -50,
  },
}
```

but figura prints:
![image](https://user-images.githubusercontent.com/25231103/149129769-3e0b49b2-e1cc-4c2d-980d-1f145d17b159.png)

**Comment by dragekk** [comment]
its not a lua issue, figura have json text support for print, log so you can use {"text":"something"} so if the first letter from print is a number then figura thinks that its json text and ignores rest

**Comment by pjalsGit** [comment]
i know, but why is this even an issue?

**Comment by dragekk** [comment]
i dont know, i remember it was fixed in some version maybe you should check if you use latest also figura have logTableContent that prints table on chat

**Comment by pjalsGit** [comment]
i know, i was just testing figura since i just downloaded it, so i wouldn't know that function, im gonna test latest figura

**Comment by pjalsGit** [comment]
updated to source code version, issue is fixed

**Comment by GNamimates** [comment]
I used to rule the world
Chunks would load when I gave the word
Now every night I go stow away
Hide from the mobs I used to slay
They once were terrified
Every time I looked into their eyes
Villagers would cheer my way
For a hero I was, that's what they'd say
One minute we had it all
Next our world began to fall
Away from all that it had once become
They all cried for my help, but I stood there numb
I gaze off into the boundless skyline
Noteblock choirs playing in the sunshine
Turn 'round pick up my sword and wield
The blade that once forced evil mobs to yield
And hope one day that this chaos and
Destruction turns for the better
Never a bow in hand
That was when I ruled the land
It was the creepers and Skeletons
Blew down the doors and boxed us in
Arrows whizzing by like streaks of light
I tried all that I could to stay and fight
As the undead roamed the street
Families broken at my feet
Life itself suspended by a thread
Oh, why is it that I wasn't dead
I gaze off into the boundless skyline
Noteblock choirs playing in the sunshine
Turn 'round pick up my sword and wield
The blade that once forced evil mobs to yield
If this battle should leave me slain
I know Herobrine will call my name
Better to take a stand
That was when I ruled the land
I gaze off into the boundless skyline
Noteblock choirs playing in the sunshine
Turn 'round pick up my sword and wield
The blade that once forced evil mobs to yield
If this battle should leave me slain
I know Herobrine will call my name
Better to take a stand
That was when I ruled the land
