### ISSUE TITLE
Figura action wheel flickering

### ISSUE THREAD

**Issue by KamiSami** [Blancworks/Figura#193]
Hi, pretty much what happens is when i try select action, i am unable to do so since while holding down the button flickers the action wheel on and off repeatedly causing mouse position reset middle of screen in so fast manner it is complete impossibility to select action... This happens with figura-0.0.7-1.18 and i got some other mods along too, i could list them if wanted.

**Comment by Francy-chan** [comment]
this bug is already fixed in the source code
