### ISSUE TITLE
Movement functions

### ISSUE THREAD

**Issue by pjalsGit** [Blancworks/Figura#194]
Since you have all these APIs, I want to make an automation script for Figura, but for that we need some new functions (you could also make this in LivingEntity, but that wouldn't make sense since Figura scripts run on players):
 - `player.walk(relative{x, y, z}, sprint)`
 - `player.fly(relative{x, y, z})` (throws error if not in creative)
 - `player.flyWithElytra(relative{x, y, z})`

If this isn't going to be added, that's ok.

**Comment by Manuel-3** [comment]
Figura is an entirely cosmetic mod and will not change any game mechanics or move your player around. If you want to automate stuff I can recommend using Baritone. Here is a simple Baritone API wrapper: https://github.com/wagyourtail/JsMacros
