### ISSUE TITLE
Having a blank sounds.json file in a model folder causes the game to crash upon selecting the model.

### ISSUE THREAD

**Issue by TTViri** [Blancworks/Figura#195]
This is exceedingly hyper-specific but I might as well put it in here, as stated in the title, the game crashes when there is a blank sounds.json file in the model's folder.

**Comment by GrandpaScout** [comment]
To add on to this,
`at net.blancworks.figura.avatar.LocalAvatarData.loadCustomSounds(LocalAvatarData.java:370)`
There seems to be no try-catch for when the file is not valid JSON.
