### ISSUE TITLE
Player Head Models on a model that does not have HEAD group cannot be modified using scripts

### ISSUE THREAD

**Issue by KabanFriends** [Blancworks/Figura#201]
Figura displays normal head part in the model when the model does not have a `HEAD` group. However, when modifying the normal head part using lua script, those changes are not affected to the player skull blocks.

Example of the issue:
lua:
```lua
model.all.Head.setScale({2.0,2.0,2.0})
```
![image](https://user-images.githubusercontent.com/45000995/151576685-0b9c82a4-ae42-45b8-83d5-04cb3dc7f918.png)
This should make the player skull twice as large, but only the player model is affected.
For reference, [this](https://github.com/KabanFriends/Touhou-Figura-Pack/tree/master/hakurei_reimu) is the model I used in the screenshot. (Note: The head scaling example code is not included)

Also, in general, I think player skull should be more customizable in lua scripts, like whether to do replace player skull with figura model or not.

**Comment by Francy-chan** [comment]
thats intended behaviour, if you want to scale the player head you must scale a children group, inside the head group
