### ISSUE TITLE
Mod detects full release of 0.0.8 when it is not available

### ISSUE THREAD

**Issue by Hibiii** [Blancworks/Figura#205]
### Environment:
- Java 17
- Minecraft 1.18.1
- Fabric Loader 0.13.2
- Fabric API 0.45.0+1.18
- Figura 0.0.7

### Steps to reproduce:
1. Open up the config menu to Figura
2. Set version update channel to full-releases
3. Click "Done".

The update indicator will remain in the avatar selection screen even after a restart.

If version 0.0.8 as full release is out, then please advise as I couldn't find it here, on CurseForge, on Modrinth and neither on the Discord guild as the mod advises.

**Comment by Francy-chan** [comment]
it is fixed at aee0b7112e79a6b32595b667e6650f8b7b87314e
