### ISSUE TITLE
uhh WHAT? (Unexpected splash text)

### ISSUE THREAD

**Issue by MCAlexisYT** [Blancworks/Figura#212]
I opened up Minecraft just to see THIS... Does this only happen on march 11? I checked into the jar file with 7-Zip and found nothing.
![uhh WHAT](https://user-images.githubusercontent.com/78766083/157859760-7f052176-05f8-4dab-9318-0dc0ca38e3a5.PNG)
This is the list of mods that I had in that specific Curseforge instance of Minecraft in case there were other mods that caused this splash text
![twmmodlist](https://user-images.githubusercontent.com/78766083/157861549-b67649d1-5453-4f71-ad53-e08f3a8e7ade.PNG)

**Comment by Stonewall0210** [comment]
Happy birthday zandra

**Comment by xzCobra** [comment]
That's supposed to happen, today is the lead(?) dev Zandra's birthday
The other devs have splash texts like that as well

**Comment by Francy-chan** [comment]
Intended behaviour;
https://github.com/Blancworks/Figura/blob/1.18/src/main/java/net/blancworks/figura/mixin/SplashTextResourceSupplierMixin.java#L40

**Comment by MCAlexisYT** [comment]
@Francy-chan ok :)

**Comment by MCAlexisYT** [comment]
Yes.
![2022-03-26_09 52 00](https://user-images.githubusercontent.com/78766083/160242573-71183bf0-4d0b-4de9-af92-2a6d74b8aeca.png)
