### ISSUE TITLE
🪲 Incompatibility with Mine Little Pony

### ISSUE THREAD

**Issue by sudofox** [Blancworks/Figura#221]
See https://github.com/MineLittlePony/MineLittlePony/issues/197

I am running Figura 0.0.8+1.18.2

This appears to be something that would need to be fixed on the Figura end:

Quote from the issue:

> _Yeah, I remember this issue coming up with Figura before. I believe it's because they override the method in their mixin which causes our code to break (a call to super.method() ends up resolving to this.method() and it becomes an infinite loop)._
> 
> _I can't fix it from my side, unfortunately._
> 
> _What I can suggest is try updating Figura or otherwise report the issue to them. I believe they were already made aware of this at some point in 1.17, but I may be mis-remembering._

**Comment by Francy-chan** [comment]
mod is still incompatible, but this issue in specific (the crash) was fixed
