### ISSUE TITLE
game crash when you open wardrobe

### ISSUE THREAD

**Issue by BlackLadGH** [Blancworks/Figura#222]
game crashed when you open wardrobe and you have more then 1 avatar

**Comment by Francy-chan** [comment]
which version of the mod are you using?

**Comment by BlackLadGH** [comment]
The new figura ui version
and this is what it say

The game crashed whilst ticking screen
Error: java.util.ConcurrentModificationException
Exit Code: -1

**Comment by Francy-chan** [comment]
new version is a test and wont be recieving bugfixes nor pull requests
