### ISSUE TITLE
Bugs with shaders and emissing textures

### ISSUE THREAD

**Issue by DelofJ** [Blancworks/Figura#225]
When using Iris Shaders and Figura and using an avatar pack that contains an emissing texture, the skin breaks when on the first person with all shaders, and on third person, it only breaks with certain shaders, tested and breaks with
BSL : first person
Complementary Shaders : first person
SEUS : both person
Sildur's Enhanced : both person
Sildur's Vibrant : first person

![bug_shaders_figura](https://user-images.githubusercontent.com/50058956/163484728-e33965f3-fcb5-46b5-bfe7-863448a40232.png)

I used :
Figura 0.0.8
Minecraft 1.18.1
Sodium 0.4.0-alpha6
Iris 1.2.0-pre

**Comment by TheNukeLore** [comment]
are you sure its figura and iris? many users use figura and iris without issue, i personally do and I use complementary as well. are you sure its not another mod causing it?

**Comment by DelofJ** [comment]
I was using a new instance created on MultiMC with only necessary mods
But i retested and it was the avatar (or the skin i don't know how to call the figura packs) that i was using that bugged, i tested with another avatar that i have found on internet and it worked, probably a bug with the emissive texture in the lua code that caused the skin to not display in first person, this time I just got the texture that doesn't emit light at the 1st person, I can't tell if it's really a bug with figura or a bug with lua code but it's probably a bug with lua code like before
Thanks for your time

**Comment by DelofJ** [comment]
Update, I fixed the previous pack and seen what's really happening
Now I'm using a test pack who works this time, everything works properly, except in 1st person
In vanilla, everythink works fine, no problems
![2022-05-11_18 24 14](https://user-images.githubusercontent.com/50058956/167899833-ccd96b3c-6c42-4d16-95aa-9a3288156bca.png)
But when you enable shaders with Iris Shaders, the skin no longer emits light
![2022-05-11_18 24 40](https://user-images.githubusercontent.com/50058956/167899856-dff969cc-2c84-4278-8092-a6c2d4f326c2.png)
I found another thing, if you use First-person Model mod (that allow you to completely see your skin like if you are in 3th person but in 1st person), even without shaders it no longer emits any light
![2022-05-11_18 23 48](https://user-images.githubusercontent.com/50058956/167899911-73d6a4cb-9262-42eb-ba72-802723fa93b7.png)
And here is what it should be
![2022-05-11_18 23 50](https://user-images.githubusercontent.com/50058956/167899975-3cb7cb32-a554-4705-9914-d07d81a34faf.png)
I think that becuse in 1st person, the rendering is different than 3th person, and that's why there are issues with 1st person

**Comment by GrandpaScout** [comment]
I can at least confirm on my side that
- Complimentary
- Enhanced Default
- Sildurs Vibrant

all cause emissive textures to stop working in first-person.
