### ISSUE TITLE
Can't find my character in Figura pannel

### ISSUE THREAD

**Issue by ElieGonzales** [Blancworks/Figura#64]
I wanted to have an animated firey head. I made an animated model, downloaded the model.bbmodel and the texture, and put it here: .minecraft/figura/model_files/firey_head
but i can't find it! Help!

**Comment by TimelordRyan** [comment]
Blockbench animations aren't supported yet, if you join the discord I believe someone has a simple animation lua script that you may be able to use.

**Comment by MCAlexisYT** [comment]
Copy-paste the following into Notepad:
`for key, value in pairs(vanilla_model) do
  value.setEnabled(false)
end`
click "Save", then open the "txt" menu, click "All Files", type **script.lua** in the text box and click "Save" on the "Save" window.

**Comment by TheOneTrueZandra** [comment]
> Copy-paste the following into Notepad:
> `for key, value in pairs(vanilla_model) do`
> ` value.setEnabled(false)`
> `end`
> click "Save", then open the "txt" menu, click "All Files", type **script.lua** in the text box and click "Save" on the "Save" window.


This has nothing to do with the initial question.

Please **make sure** the texture is called texture.png and the model is model.bbmodel
