### ISSUE TITLE
Bug: NO_PARENT parts don't animate in first person

### ISSUE THREAD

**Issue by Manuel-3** [Blancworks/Figura#78]
NO_PARENT parts are visible, but don't animate in first person (lua script). They are animated tho, when opening an inventory or getting hurt. In third person it works fine (both front and back).

**Comment by Francy-chan** [comment]
the bug only happens when not rendering the player entity
eg. when holding a item on the mainhand (except maps)
so the player rendering script is not executed

**Comment by TheOneTrueZandra** [comment]
We should make render() call every frame, honestly, and make a new function for when a hand is rendering

**Comment by Manuel-3** [comment]
What would this new function be called? The name kind of implies that it is called when something renders, maybe update() for every frame and keep render() like that?

**Comment by TheOneTrueZandra** [comment]
renderHand probably??

**Comment by Manuel-3** [comment]
I mean... render() already has this behavior, it is called when some part of the player is rendered. So it would make sense to just keep it like that and instead make a new function that actually gets called every frame.
