### ISSUE TITLE
Avatar not loading properly

### ISSUE THREAD

**Issue by randomlyGenerated-0** [Blancworks/Figura#88]
I did everything for a basic avatar, there's no script and it wont load.
Image : https://i.gyazo.com/55f115ff46bc829c99490d2805352d79.png

I'll attach an avatar and texture.
https://www.mediafire.com/file/z7qa9nh2pbapbuj/skin.zip/file

**Comment by TheOneTrueZandra** [comment]
Not technically a bug. Blockbench uses CLAMPED textures, Figura uses WRAPPED.

Move the staff UV so that it's not outside of the texture area in blockbench.
